### ISSUE TITLE
Call to undefined method Tax::clearRates()

### ISSUE THREAD

**Issue by joaovieiraandrade** [Dreamvention/2_d_quickcheckout_lite#24]
Hello guys! I got this error on the checkout page, does anyone know the solution or has the same error?
![tax-error](https://cloud.githubusercontent.com/assets/16733768/12719683/df645f4c-c8dd-11e5-94bb-79832e6943bf.jpg)

**Comment by Dreamvention** [comment]
Hi this issue has been resolved in the latest updates. thank you for your feedback

**Comment by Yakubina** [comment]
Hi, I`m facing with the same problem with latest version 6.4.6

> Fatal error: Uncaught Error: Call to undefined method Cart\Tax::clearRates() in /var/www/html/catalog/model/d_quickcheckout/address.php:40 Stack trace: #0 /var/www/html/system/engine/loader.php(178): ModelDQuickcheckoutAddress->updateTaxAddress() #1 /var/www/html/system/engine/proxy.php(25): Loader->{closure}(Array, Array) #2 /var/www/html/catalog/controller/module/d_quickcheckout.php(361): Proxy->__call('updateTaxAddres...', Array) #3 /var/www/html/catalog/controller/module/d_quickcheckout.php(45): ControllerModuleDQuickcheckout->initialize() #4 /var/www/html/system/engine/action.php(51): ControllerModuleDQuickcheckout->index(Array) #5 /var/www/html/system/engine/loader.php(24): Action->execute(Object(Registry), Array) #6 /var/www/html/catalog/controller/checkout/checkout.php(96): Loader->controller('module/d_quickc...') #7 /var/www/html/system/engine/action.php(51): ControllerCheckoutCheckout->index() #8 /var/www/html/catalog/controller/startup/router.php(25): Action->execute(Object(Registry)) #9 /var/www/html/system/en in /var/www/html/catalog/model/d_quickcheckout/address.php on line 40
